name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Super-Linter
        run: |
          # run pipeline

          export DB_PATH=/home/runner/work/flask_web_app/flask_web_app/database/database.db
          echo Finished exporting DB_PATH
          echo $DB_PATH

          if [ ! -d "database" ]
          then
            mkdir database
            if [ $? -ne 0 ]
            then
              echo "FATAL: database created unsuccessfully"
              exit 1
            fi
          fi
          yes | sudo apt install python3 && sudo apt install python3-pip && sudo pip3 install flask && sudo pip3 install flask-login && sudo pip3 install flask-sqlalchemy
          if [ $? -ne 0 ]
          then
            echo "FATAL: packages downloaded unsuccessfully"
            exit 2
          fi

          nohup python3 main.py > console.log &
          if [ $? -ne 0 ]
          then
            echo FATAL: application runned unsuccessfully
            exit 3
          fi
          echo SUCCESS
          ls
          pwd

