name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

      - name: Run Super-Linter
        run: |
        # hello world
          echo ________00000000000___________000000000000_________
          echo ______00000000_____00000___000000_____0000000______
          echo ____0000000_____________000______________00000_____
          echo ___0000000_______________0_________________0000____
          echo __000000____________________________________0000___
          echo __00000_____________________________________ 0000__
          echo _00000______________________________________00000__
          echo _00000_____________________________________000000__
          echo __000000_________________________________0000000___
          echo ___0000000______________________________0000000____
          echo _____000000____________________________000000______
          echo _______000000________________________000000________
          echo __________00000_____________________0000___________
          echo _____________0000_________________0000_____________
          echo _______________0000_____________000________________
          echo _________________000_________000___________________
          echo _________________ __000_____00_____________________
          echo ______________________00__00_______________________
          echo ________________________00_________________________

        
