name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

      - name: Run Super-Linter
        run: |
          # run pipeline

          if [ ! -d "database" ]
          then
            mkdir database
            if [ $? -ne 0 ]
            then
              echo "FATAL: /database created unsuccessfully"
              exit 1
            fi
          fi
          yes | apt install python3 && apt install python3-pip && pip3 install flask && pip3 install flask-login && pip3 install flask-sqlalchemy
          if [ $? -ne 0 ]
          then
            echo "FATAL: packages downloaded unsuccessfully"
            exit 2
          fi

          export DB_PATH=database/database.db

          wget https://github.com/James-Yu-2007/flask_web_app/archive/refs/tags/v1.3.zip && unzip v1.3.zip && rm v1.3.zip && nohup python3 flask_web_app-1.3/main.py > console.log &
          if [ $? -ne 0 ]
          then
            echo "FATAL: website published unsuccessfully"
            exit 3
          fi
          echo SUCCESS
