name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:

      - name: Run Super-Linter
        run: |
          # secret
          if [ "$SECRET_TEST" == "secret" ]
          then
            echo Got Secret
          fi
        env:
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
